### ISSUE TITLE
Guide user what to ask after listing speakers

### ISSUE THREAD

**Issue by ronnelsantiago** [luizbon/ConferenceBot#10]
Would be good if user say `give me list of speakers`  and they guiding them what other possible `commands` they can say to the bot.

**Comment by luizbon** [comment]
Done as part of commit [67916b284b292dae3fff956afae63bac878b5670 ](https://github.com/luizbon/ConferenceBot/commit/67916b284b292dae3fff956afae63bac878b5670)
